version: '3.8'

services:
  backend:
    image: dimkablin/s2t-factory-backend
    environment:
      - SSL_KEY=/app/ssl/local_key.pem
      - SSL_CERT=/app/ssl/local_cert.pem
    volumes:
      - ./backend/ssl:/app/ssl:ro
      - ./backend/.env:/app/.env:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend:/app
      - ./docker-compose.yml:/app/docker-compose.yml

    ports:
      - "8000:8000"
    depends_on:
      - speech2text-whisper-medium
      - speech2text-whisper-small

  frontend:
    image: dimkablin/s2t-factory-frontend
    environment:
      - SSL_KEY=/app/ssl/local_key.pem
      - SSL_CERT=/app/ssl/local_cert.pem
    volumes:
      - ./frontend/ssl:/app/ssl:ro
      - ./frontend/.env:/app/.env:ro
    ports:
      - "8001:8001"
    depends_on:
      - backend
    
  speech2text-whisper-small:
    image: dimkablin/speech2text
    environment:
      - MODEL_NAME=openai/whisper-small
      - USE_CUDA=True
      - PORT=8002
    # ports:
    #   - "8002:8002"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  speech2text-whisper-medium:
    image: dimkablin/speech2text
    environment:
      - MODEL_NAME=openai/whisper-medium
      - USE_CUDA=True
      - PORT=8003
    ports:
      - "8003:8003"
    
  speech2text-whisper-tiny:
    image: dimkablin/speech2text
    environment:
      - MODEL_NAME=openai/whisper-tiny
      - USE_CUDA=False
      - PORT=8004
  
  speech2text-whisper-base:
    image: dimkablin/speech2text
    environment:
      - MODEL_NAME=openai/whisper-base
      - USE_CUDA=False
      - PORT=8005

